--- #YAML:1.0
module_name: CPAN-Tester
dist_version_from: lib/CPAN/Tester.pm
installdirs: site
requires:
    Carp: 		 0
    ExtUtils::MakeMaker: 0
    File::Slurp: 	 0
    Getopt::Long: 	 0
    Net::FTP: 		 0
    Test::Reporter: 	 0
distribution_type: module
license: perl
dist_abstract: Test CPAN contributions and submit reports to cpan-testers@perl.org
